{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.redis.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cache: |
          ADAPTER=redis
          HOST=redis://:{{ `{{ .password | urlquery }}` }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/0
        session: |
          PROVIDER=redis
          PROVIDER_CONFIG=redis://:{{ `{{ .password | urlquery }}` }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/1
        queue: |
          TYPE=redis
          CONN_STR=redis://:{{ `{{ .password | urlquery }}` }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/2
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.redis.remotePasswordKey }}
{{- end }}
