{{- if .Values.smtp.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.smtp.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: smtp
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: forgejo-smtp-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mailer: |
          ENABLED=true
          FROM={{ .Values.smtp.from }}
          PROTOCOL={{ .Values.smtp.protocol }}
          SMTP_ADDR={{ .Values.smtp.host }}
          SMTP_PORT={{ .Values.smtp.port }}
          USER={{ `{{ .username }}` }}
          PASSWD={{ `{{ .password }}` }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.smtp.remoteUsernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.smtp.remotePasswordKey }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admin
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo-admin-username
    - secretKey: password
      remoteRef:
        key: forgejo-admin-password
