{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: github-arc-auth
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.appId }}
    - secretKey: github_app_installation_id
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.installationId }}
    - secretKey: github_app_private_key
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.privateKey }}
{{- end }}
