replicaCount: 2

vikunjaEnvironment:
- name: VIKUNJA_SERVICE_PUBLICURL
  value: https://vikunja.labgrid.net
- name: VIKUNJA_DATABASE_TYPE
  value: "postgres"
- name: DB_POSTGRESDB_HOST
  valueFrom:
    secretKeyRef:
      name: vikunja-stg-pgcluster-app
      key: host
- name: DB_POSTGRESDB_PORT
  valueFrom:
    secretKeyRef:
      name: vikunja-stg-pgcluster-app
      key: port
- name: VIKUNJA_DATABASE_DATABASE
  valueFrom:
    secretKeyRef:
      name: vikunja-stg-pgcluster-app
      key: dbname
- name: VIKUNJA_DATABASE_USER
  valueFrom:
    secretKeyRef:
      name: vikunja-stg-pgcluster-app
      key: username
- name: VIKUNJA_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: vikunja-stg-pgcluster-app
      key: password

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: vikunja.labgrid.net
      paths:
        - path: /
          pathType: ImplementationSpecific


# Additional volumes on the output Deployment definition.
volumes:
- name: vikunja-data
  persistentVolumeClaim:
    claimName: vikunja-storage

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: vikunja-data
  mountPath: "/home/node/.vikunja"

nodeSelector: {}

tolerations: []

affinity: {}


persistentVolumeClaim:
  create: true
  accessMode: ReadWriteMany
  volumeMode: Filesystem
  size: 1Gi
  storageClassName: "synology-nfs-delete"
  existingPersistentVolumeClaim: ''
  annotations: {}
  # -- Additional labels for the persistent volume claim object.
  labels: {}

databaseCredential:
  secretName: vikunja-pgcluster-app

initContainer:
  command:
    - sh
    - -c
    - |
      until pg_isready -h "$VIKUNJA_PGCLUSTER_RW_SERVICE_HOST" -p 5432; do 
        echo Waiting for the database to be ready...; 
        sleep 5; 
      done;


pgcluster:
  enabled: true
  type: postgresql

  version:
    # -- PostgreSQL major version to use
    postgresql: "17"

  mode: standalone

  cluster:
    instances: 1
    imageName: "ghcr.io/cloudnative-pg/postgresql:17.2"
    imagePullPolicy: IfNotPresent

    storage:
      size: 8Gi
      storageClass: "synology-nfs-delete"

    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "2"

    priorityClassName: ""
    primaryUpdateMethod: switchover
    primaryUpdateStrategy: unsupervised
    logLevel: "info"

    affinity:
      enablePodAntiAffinity: true
      topologyKey: topology.kubernetes.io/zone

    enableSuperuserAccess: true

    enablePDB: true

    initdb:
      database: "vikunja"
      owner: "labgridappuser"


  backups:
    enabled: true

  externalSecretBackupCredentials:
    enabled: true
