keycloak:
  global:
    defaultStorageClass: "synology-iscsi-delete"
  replicaCount: 2
  image:
    debug: false
  production: true
  externalDatabase:
    existingSecret: "iam-pgcluster-app"

  initContainers:
    - name: wait-for-postgres-cluster
      image: postgres:latest
      command:
        - sh
        - -c
        - |
          until pg_isready -h "$IAM_PGCLUSTER_RW_SERVICE_HOST" -p 5432; do 
            echo Waiting for the database to be ready...; 
            sleep 5; 
          done;

  ingress:
    enabled: true
    hostnameStrict: true
    hostname: "iam.labgrid.net"
    ingressClassName: "nginx"
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls: true
    extraHosts:
      - name: "iam.local.labgrid.net"
        path: "/"


pgcluster:
  instances: 2
  storage:
    storageClass: "synology-iscsi-delete"
    size: "1Gi"
