keycloak:
  global:
    defaultStorageClass: "local-path"
  replicaCount: 1
  image:
    debug: true

  externalDatabase:
    existingSecret: "iam-stg-pgcluster-app"

  initContainers:
    - name: wait-for-postgres-cluster
      image: postgres:latest
      command:
        - sh
        - -c
        - |
          until pg_isready -h "$IAM_STG_PGCLUSTER_RW_SERVICE_HOST" -p 5432; do 
            echo Waiting for the database to be ready...; 
            sleep 5; 
          done;

  ingress:
    enabled: true
    hostnameStrict: true
    hostname: "iam.stg.local.labgrid.net"
    ingressClassName: "nginx"
    path: "/"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls: true
    extraHosts:
      - name: "iam.stg.labgrid.net"
        path: "/" 

  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: DEBUG

# Maybe removed as it not being used
keycloakCertificate:
  commonName: "iam.stg.local.labgrid.net"
  dnsNames:
    - "iam.stg.labgrid.net"
    - "iam.stg.local.labgrid.net"

pgcluster:
  instances: 1
  storage:
    storageClass: "local-path"
    size: "0.5Gi"

  backup:
    enabled: false
