keycloak:
  global:
    defaultStorageClass: "synology-iscsi-delete"
  replicaCount: 2
  image:
    debug: false
  production: true
  externalDatabase:
    existingSecret: "iam-pgcluster-app"

  initContainers:
    - name: wait-for-postgres-cluster
      command:
        - sh
        - -c
        - |
          until pg_isready -h "$IAM-PGCLUSTER_RW_SERVICE_HOST" -p 5432; do 
            echo Waiting for the database to be ready...; 
            sleep 5; 
          done;


pgcluster:
  instances: 2
  storage:
    storageClass: "synology-iscsi-delete"
    size: "1Gi" 


  backup:
    barmanObjectStore:
      destinationPath: "https://labgrid.blob.core.windows.net/labgrid-iam"
      azureCredentials:
        storageAccount:
          name: "azure-credential"
          key: "labgrid-storage-account-name"
        storageSasToken:
          name: "azure-credential"
          key: "labgrid-blob-sas-token"
      wal:
        compression: "gzip"
        encryption: "AES256"
      data:
        compression: "gzip"
        encryption: "AES256"
    retentionPolicy: "14d"
