apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tdai-memory.hub.fullname" . }}-knowledge
  labels:
    {{- include "tdai-memory.hub.labels" . | nindent 4 }}
  {{- with .Values.hub.persistentVolumeClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.hub.persistentVolumeClaim.accessMode }}
  volumeMode: {{ .Values.hub.persistentVolumeClaim.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.hub.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.hub.persistentVolumeClaim.storageClassName }}
