{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.rabbitmq.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: {{ .Values.externalSecrets.rabbitmq.username | quote }}
        password: "{{ `{{ .password }}` }}"
        .erlang.cookie: "{{ `{{ .erlangcookie }}` }}"
        default_user.conf: |
          default_user = {{ .Values.externalSecrets.rabbitmq.username }}
          default_pass = {{ `{{ .password }}` }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.rabbitmq.remotePasswordKey }}
    - secretKey: erlangcookie
      remoteRef:
        key: {{ .Values.externalSecrets.rabbitmq.remoteErlangCookieKey }}
{{- end }}
