{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.rabbitmq.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.rabbitmq.passwordKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.rabbitmq.remotePasswordKey }}
    - secretKey: {{ .Values.externalSecrets.rabbitmq.erlangCookieKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.rabbitmq.remoteErlangCookieKey }}
{{- end }}
