redis:
  architecture: replication

  auth:
    enabled: true
    sentinel: true
    existingSecret: "redis-credentials"
    existingSecretPasswordKey: "REDIS_PASSWORD"
    usePasswordFiles: true

  volumePermissions:
    enabled: true

  sentinel:
    enabled: false
    masterSet: mymaster
    quorum: 2
    downAfterMilliseconds: 60000
    failoverTimeout: 180000
    parallelSyncs: 1
    automateClusterRecovery: true
    redisShutdownWaitFailover: true
    tls:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  master:
    service:
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "synology-iscsi-delete"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: Always
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true

  replica:
    replicaCount: 2
    service:
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "synology-iscsi-delete"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: Always
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true

  tls:
    enabled: false


# TLS Certificate Configuration (for cert-manager)
tls:
  enabled: false
  authClients: false
  autoGenerated: false
  existingSecret: "redis-tls"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: ""
  # Certificate configuration for cert-manager
  issuerRef:
    name: "letsencrypt-production"
    kind: "ClusterIssuer"
  dnsNames:
    - "redis.labgrid.net"
    - "redis-local.labgrid.net"
  privateKey:
    algorithm: "RSA"
    size: 2048
  duration: "2160h"  # 90 days
  renewBefore: "360h"  # 15 days

# External Secrets for credentials
externalSecretCredentials:
  enabled: true
  name: redis-credentials
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
