externalSecrets:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  redis:
    name: redis-credentials
    passwordKey: redis-password
    remotePasswordKey: platform-redis-password

redis:
  architecture: standalone
  config:
    content: |
      # Redis configuration
      bind * -::*
      notify-keyspace-events Ex
  auth:
    enabled: true
    existingSecret: redis-credentials
    existingSecretPasswordKey: redis-password
  persistence:
    enabled: true
    storageClass: synology-iscsi-delete-wffc
    size: 5Gi
  service:
    type: ClusterIP
