redis:
  # Production values for Redis
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Redis Architecture - Master-Replica with Sentinel
  architecture: replication

  # Authentication (managed via External Secrets)
  auth:
    enabled: true
    sentinel: true
    password: ""
    existingSecret: "redis-credentials"
    existingSecretPasswordKey: "REDIS_PASSWORD"
    usePasswordFiles: true
    usePasswordFileFromSecret: true

  volumePermissions:
    enabled: true

  # Common Configuration (AOF persistence enabled by default)
  # commonConfiguration: |-
  #   dir /bitnami/redis/data
  #   appendonly yes
  #   appendfsync everysec

  # Sentinel Configuration
  sentinel:
    enabled: true
    masterSet: mymaster
    quorum: 2
    downAfterMilliseconds: 60000
    failoverTimeout: 180000
    parallelSyncs: 1
    automateClusterRecovery: true
    redisShutdownWaitFailover: true
    # Disable TLS for Sentinel
    tls:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  # Master Configuration
  master:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "synology-iscsi-delete"
      path: /data
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    podAntiAffinityPreset: soft
    nodeSelector: {}
    tolerations: []
    affinity: {}
    # Fix permissions for AOF directory
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: Always
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true

  # Replica Configuration
  replica:
    replicaCount: 2
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "synology-iscsi-delete"
      path: /data
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    podAntiAffinityPreset: soft
    nodeSelector: {}
    tolerations: []
    affinity: {}
    # Fix permissions for AOF directory
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: Always
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true

  # Monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s

  # Network Policy
  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true

  # Namespace override (if needed)
  namespaceOverride: ""

  # TLS Configuration for Redis
  tls:
    enabled: false
    authClients: false
    autoGenerated: false
    existingSecret: "redis-tls"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    certCAFilename: ""

# TLS Certificate Configuration (for cert-manager)
tls:
  enabled: true
  authClients: false
  autoGenerated: false
  existingSecret: "redis-tls"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: ""
  # Certificate configuration for cert-manager
  issuerRef:
    name: "letsencrypt-production"
    kind: "ClusterIssuer"
  dnsNames:
    - "redis.labgrid.net"
    - "redis-local.labgrid.net"
  privateKey:
    algorithm: "RSA"
    size: 2048
  duration: "2160h"  # 90 days
  renewBefore: "360h"  # 15 days

# External Secrets for credentials
externalSecretCredentials:
  enabled: true
  name: redis-credentials
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
