# Default values for Redis
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Redis Architecture - Master-Replica with Sentinel
architecture: replication

# Authentication
auth:
  enabled: true
  sentinel: true
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
  usePasswordFiles: true
  usePasswordFileFromSecret: true

# Common Configuration (AOF persistence enabled by default)
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""

# Sentinel Configuration
sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  parallelSyncs: 1
  automateClusterRecovery: true
  redisShutdownWaitFailover: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Master Configuration
master:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "synology-iscsi-delete"
    path: /data
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  podAntiAffinityPreset: soft
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Replica Configuration
replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "synology-iscsi-delete"
    path: /data
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  podAntiAffinityPreset: soft
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

# Network Policy
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true

# Namespace override (if needed)
namespaceOverride: ""

# TLS Configuration
tls:
  enabled: true
  authClients: true
  autoGenerated: false
  existingSecret: "redis-tls"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: "ca.crt"
  # Certificate configuration for cert-manager
  issuerRef:
    name: "letsencrypt-production"
    kind: "ClusterIssuer"
  dnsNames:
    - "redis.labgrid.net"
    - "redis.local.labgrid.net"
    # Internal DNS names for cluster access
    - "redis-master.redis-system.svc.cluster.local"
    - "redis-master.redis-system.svc"
    - "redis-master.redis-system"
    - "redis-master"
  privateKey:
    algorithm: "RSA"
    size: 2048
  duration: "2160h"  # 90 days
  renewBefore: "360h"  # 15 days

# External Secrets for credentials
externalSecretCredentials:
  enabled: true
  name: redis-credentials
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
