{{- if and .Values.alloy.enabled .Values.alloyFaroIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-alloy-faro" .Release.Name }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
  labels:
    app.kubernetes.io/name: {{ include "monitoring.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: alloy-faro
  {{- with .Values.alloyFaroIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.alloyFaroIngress.ingressClassName | quote }}
  {{- if .Values.alloyFaroIngress.tls }}
  tls:
    {{- range .Values.alloyFaroIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.alloyFaroIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.alloyFaroIngress.serviceName | quote }}
                port:
                  number: {{ .Values.alloyFaroIngress.servicePort }}
{{- end }}
