apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkding.fullname" . }}
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linkding.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linkding.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-postgres-cluster
        image: postgres:latest
        command:
          - sh
          - -c
          - |
            until pg_isready -h "$PGCLUSTER_RW_SERVICE_HOST" -p 5432; do 
              echo Waiting for the database to be ready...; 
              sleep 5; 
            done;
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: UTC
            # PostgreSQL Configuration
            - name: LD_DB_ENGINE
              value: postgresql
            - name: LD_DB_DATABASE
              value: linkding
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-pgcluster-app # Auto-created by CNPG
                  key: username
            - name: LD_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: linkding-pgcluster-app # Auto-created by CNPG
                  key: host
            - name: LD_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: linkding-pgcluster-app # Auto-created by CNPG
                  key: port
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-pgcluster-app # Auto-created by CNPG
                  key: password
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
