{{- if .Values.keycloakCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.keycloakCertificate.name | quote }}
  namespace: {{ .Release.Namespace | default .Values.namespaceOverride }}
spec:
  secretName: {{ .Values.keycloakCertificate.secretName | quote }}
  issuerRef:
    name: {{ .Values.keycloakCertificate.issuerRef.name | quote }}
    kind: {{ .Values.keycloakCertificate.issuerRef.kind | quote }}
  commonName: {{ .Values.keycloakCertificate.commonName | quote }}
  dnsNames:
  {{- range .Values.keycloakCertificate.dnsNames }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
