apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trillium-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: "synology-iscsi-delete"