apiVersion: v2
name: rabbitmq
description: RabbitmqCluster instance for Labgrid (requires rabbitmq-cluster-operator)
type: application
version: 0.2.0
appVersion: "4.3.4"
maintainers:
  - name: LabGrid Labs
    email: admin@labgrid.net
