externalSecrets:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  rabbitmq:
    name: rabbitmq-credentials
    passwordKey: password
    remotePasswordKey: platform-rabbitmq-password
    erlangCookieKey: erlang-cookie
    remoteErlangCookieKey: platform-rabbitmq-erlang-cookie

rabbitmq:
  replicaCount: 1
  auth:
    enabled: true
    username: admin
    existingSecret: rabbitmq-credentials
    existingPasswordKey: password
    existingErlangCookieKey: erlang-cookie
  persistence:
    enabled: true
    storageClass: synology-iscsi-delete-wffc
    size: 5Gi
  service:
    type: ClusterIP
