configs:
  cm:
    exec.enabled: true
  params:
    server.insecure: true

server:
  certificate:
    enabled: true
    secretName: argocd-server-tls
    domain: "labgrid.net"

    issuer:
      group: "cert-manager.io"
      kind: "ClusterIssuer"
      name: "letsencrypt"

  ingress:
    enabled: true

    ingressClassName: "nginx"

    hostname: "argocd.local.labgrid.net"

    tls: true

    extraHosts:
      - name: argocd.labgrid.net
        path: /