apiVersion: v2
name: gha-runners
description: GitHub Actions runner scale set (labgrid) with ExternalSecret for Labgrid
type: application
version: 0.1.0
appVersion: "0.14.2"
dependencies:
  - name: gha-runner-scale-set
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
maintainers:
  - name: LabGrid Labs
    email: admin@labgrid.net
    url: blog.labgrid.net
