name: Kubernetes environment workflow

on:
    workflow_dispatch: 
    push: 
        branches: 
            - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubeconfig from the GitHub Secret
      - name: Get OIDC Token from Keycloak
        run: |
            TOKEN=$(curl -X POST \
            ${{ secrets.KEYCLOAK_ISSUER_URL }}/protocol/openid-connect/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=github-actions" \
            -d "client_secret=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" | jq -r '.access_token')
            echo $TOKEN 
            echo "OIDC_TOKEN=$TOKEN" >> $GITHUB_ENV
        
      - name: Authenticate to Kubernetes
        run: |
            kubectl config set-credentials github-action-user --token=$OIDC_TOKEN
            kubectl config set-cluster my-cluster --server=https://<kubernetes-api-server-url>
            kubectl config set-context my-context --cluster=my-cluster --user=github-action-user
            kubectl config use-context my-context

      # Verify kubectl is installed and check version
      - name: Check kubectl version
        run: kubectl version --client

      - name: List pods in the cluster
        run: kubectl get pods

              


