name: Kubernetes environment workflow

on:
    workflow_dispatch: 
    push: 
        branches: 
            - feature/*
jobs:
    kubernetes:
        runs-on: ubuntu-latest
        steps:
        - uses: actions-hub/kubectl@master
          env:
            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          with:
            args: get nodes
              


