name: Kubernetes environment workflow

on:
    workflow_dispatch: 
    push: 
        branches: 
            - feature/*
jobs:
    kubernetes:
        runs-on: ubuntu-latest
        steps:
        - uses: tale/kubectl-action@v1
          with:
            base64-kube-config: ${{ secrets.KUBE_CONFIG }}
        - name: List nodes on cluster
          run: kubectl get nodes
              


